language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: y+RZ5xmsJn1PkMOG0vk11ze3TbEZ6vU4lNhAlD8jnbSJ0TX5R3RuZtzhtin4bI4PuhlhxIHFQ8FUgguLCohQK2iNmn6I7CFbXOA5asLjG6x1IV6pKA7bA3jJ9ZRhYgLZLOcww9mhwPFyO/j9yVZ1Fn+groNUdA7iwMvdzM8CPzP8geUplenXheFqeqN/l/LOMdO+67NW5LtWT+G52JRt/U1OfYLMfRXGxBxmww4OJtXhDKihn7ZeHrZkXfRRfcnAi6FfdM93C53ewm0BKBGdga59IlaMdM5NARzOCGHHuV+A/KZ5vShobbzBeNCGQKdmbfXCiQBxhdX1iGWHsLDYl/+uQz/1RwlrGQxb4iyo+6ROXXnBLoE3GVC06XPtMi6q9FzAL6CGyTmFvuan8U48v109X48fL1nNA2/BPlmdbZ2uV6azQExbH0yxZCGe0eFF5jPcFdkVjF5tpIQ71a9cavx46/9BB0MOwwD7RQdvLzJQtkOGRa/11AvWDkB1lGAiZEfpslmjhLvHJvhzMeePopfBrLB7VVnBb/dU7VKleAhJxHIJ0VpCM0YXDUwqKtIbEbYk9DcOpcuJwOQ0P5+9ts/i7JgC0eETbHbMzLfEGJVlOgPhqjlijbQdb/Nx4dmq46IRyseGm5Pp/ITt6pTQpop5npFqOR3ePmxjqJQFiaU=
  app: micro-donate
  on:
    repo: uva-cs3240-f20/project-1-31
