# Generated by Django 3.0.2 on 2020-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='donate_user',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_user',
        ),
        migrations.AddField(
            model_name='donate',
            name='donate_users',
            field=models.ManyToManyField(to='microdonate.Profile'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_users',
            field=models.ManyToManyField(to='microdonate.Profile'),
        ),
    ]
