# Generated by Django 3.0.5 on 2020-10-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0002_auto_20201019_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='goal',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='organization_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
