# Generated by Django 3.0.5 on 2020-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0003_auto_20201030_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_title', models.CharField(max_length=200)),
                ('comments_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
