# Generated by Django 3.1.1 on 2020-11-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='donate',
            name='goal',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='donate',
            name='organization_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
