# Generated by Django 3.1.1 on 2020-11-09 02:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0006_auto_20201108_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 2, 25, 8, 898057, tzinfo=utc), verbose_name='Date of Event'),
        ),
    ]
