# Generated by Django 3.0.5 on 2020-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0008_auto_20201124_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='volunteer_users',
            field=models.ManyToManyField(to='microdonate.Profile'),
        ),
    ]
