# Generated by Django 3.0.5 on 2020-11-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0010_auto_20201124_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='comments',
            field=models.ManyToManyField(to='microdonate.Comments'),
        ),
        migrations.DeleteModel(
            name='DonateComments',
        ),
    ]
