# Generated by Django 3.0.5 on 2020-11-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdonate', '0011_auto_20201124_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='comments',
            field=models.ManyToManyField(to='microdonate.Comments'),
        ),
    ]
